### ISSUE TITLE
Переход из локации в локацию может требовать не еденичного нажатия на движение.

### ISSUE THREAD

**Issue by dart-chiker** [pindos11/tkinter-roguelike#5]
То если пытаться перейти с локации на другую не в середине карты, то нужно нажать 2-3 раза перед тем как герой перейдет на ту локацию.

Если переходить в середине данное поведение не наблюдается.

(Подозреваю, что это из-за того, что пытаются загенериться пустынные или "космические" локации в которых проход только в середине. Это подтверждатеся тем, что если так ходить, то генеряться только зеленые и красные)

**Comment by pindos11** [comment]
Я кстати эту проблему заметил ещё когда все было одним файлом. Я пофикшу

**Comment by pindos11** [comment]
решено, сверху упоминание в коммите
все остальное, релейтед к этой ишуе в #8
